const JWT_SECRET = "123456";
const JWT_EXPIRATION = "1h";
const REFRESH_TOKEN_EXPIRATION = "7d";
const TELEGRAM_BOT_TOKEN = "token";

module.exports = {
  JWT_SECRET,
  JWT_EXPIRATION,
  REFRESH_TOKEN_EXPIRATION,
  TELEGRAM_BOT_TOKEN,
};
